SET TERM ^ ;

CREATE OR ALTER PROCEDURE SPHINXCLIENT$EXECUTE (
    SQL_TEXT VARCHAR(8000) CHARACTER SET UTF8 NOT NULL)
RETURNS (
    MODULE_ID BIGINT,
    ROW_ID VARCHAR(128) CHARACTER SET OCTETS)
EXTERNAL NAME 'udr_SphinxClient!Execute'
ENGINE UDR
^

CREATE OR ALTER FUNCTION SPHINXCLIENT$QUOTEDSTR (
   IN_STR VARCHAR(255) CHARACTER SET UTF8 NOT NULL)
RETURNS VARCHAR(255) CHARACTER SET UTF8
EXTERNAL NAME 'udr_SphinxClient!QuotedStr'
ENGINE UDR
^

SET TERM ; ^
