EXECUTE BLOCK RETURNS (
  MODULE_ID INTEGER, 
  ROW_ID    VARCHAR(128) CHARACTER SET OCTETS
)
AS
DECLARE VARIABLE SQL_TEXT VARCHAR(8000);
BEGIN
  SQL_TEXT =
    'SELECT MODULE_ID, ROW_ID FROM Cashs2_Operations ' ||
    'WHERE MATCH(''иванов иван владимирович'')' ||
    '  AND TDATE BETWEEN 42000 AND 50000';
  FOR
    SELECT MODULE_ID, ROW_ID
    FROM SPHINXSEARCH$EXECUTE(:SQL_TEXT)
    INTO :MODULE_ID, :ROW_ID
  DO
  BEGIN
    SUSPEND;
  END
END

