/******************************************************************************/
/***                         User Defined Functions                         ***/
/******************************************************************************/

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$CREATE
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'ClientCreate' MODULE_NAME 'udf_SphinxClient';

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$FREE
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'ClientFree' MODULE_NAME 'udf_SphinxClient';

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$NEXT
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'ClientNext' MODULE_NAME 'udf_SphinxClient';

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$EOF
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'ClientEOF' MODULE_NAME 'udf_SphinxClient';

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$EXEC_SQL
    INTEGER,
    CSTRING(8000) CHARACTER SET UTF8
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'ClientExecSQL' MODULE_NAME 'udf_SphinxClient';

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$CURRENT_VALUE
    INTEGER,
    INTEGER,
    CSTRING(128) CHARACTER SET OCTETS
    RETURNS PARAMETER 3
    ENTRY_POINT 'ClientGetCurrentValue' MODULE_NAME 'udf_SphinxClient';

DECLARE EXTERNAL FUNCTION SPHINXCLIENT$QUOTEDSTR
    CSTRING(255) CHARACTER SET UTF8,
    CSTRING(255) CHARACTER SET UTF8
    RETURNS PARAMETER 2
    ENTRY_POINT 'QuotedStr' MODULE_NAME 'udf_SphinxClient';
