EXECUTE BLOCK RETURNS (
  PARSER_ID INTEGER,
  MODULE_ID INTEGER, 
  WEIGHT    INTEGER,
  ROW_ID    VARCHAR(128) CHARACTER SET OCTETS
)
AS
DECLARE VARIABLE SQL_TEXT VARCHAR(8000);
BEGIN
  SQL_TEXT =
    'SELECT MODULE_ID, ROW_ID, WEIGHT() FROM Cashs2_Operations ' ||
    'WHERE MATCH(''иванов иван владимирович'')' ||
    '  AND TDATE BETWEEN 42000 AND 50000';
  PARSER_ID = SPHINXCLIENT$CREATE();
  IF (SPHINXCLIENT$EXEC_SQL(PARSER_ID, SQL_TEXT) = 1) THEN
  BEGIN
    WHILE (SPHINXCLIENT$EOF(PARSER_ID) = 1) DO
    BEGIN
      MODULE_ID = SPHINXCLIENT$CURRENT_VALUE(PARSER_ID, 0);
      ROW_ID    = SPHINXCLIENT$CURRENT_VALUE(PARSER_ID, 1);
      WEIGHT    = SPHINXCLIENT$CURRENT_VALUE(PARSER_ID, 2);
      SUSPEND;
      SPHINXCLIENT$NEXT(PARSER_ID);
    END
  END
  SPHINXCLIENT$FREE(PARSER_ID);
END

